export const DIAGNOSTIC_MANIFEST_SCHEMA_VERSION = "diagnostic-manifest-v1" as const;
export const DIAGNOSTIC_COLLECTION_POLICY_VERSION = "diagnostic-collection-policy-v1" as const;
export const DIAGNOSTIC_ERROR_AGGREGATION_VERSION = "diagnostic-error-aggregation-v1" as const;
export const DIAGNOSTIC_REVIEW_DIRECTORY_VERSION = "diagnostic-review-directory-v1" as const;

export const DIAGNOSTIC_IDENTIFIER_PREFIX_LENGTH = 12;
export const DIAGNOSTIC_HMAC_PREFIX_LENGTH = 16;

export const DIAGNOSTIC_WARNING_CODES = [
  "EE_DIAGNOSTIC_DATABASE_UNAVAILABLE",
  "EE_DIAGNOSTIC_DATABASE_INSPECTION_FAILED",
  "EE_DIAGNOSTIC_IDENTITY_UNAVAILABLE",
  "EE_DIAGNOSTIC_INSTALL_ATTESTATION_UNAVAILABLE",
  "EE_DIAGNOSTIC_HOST_INSPECTION_FAILED"
] as const;

export type DiagnosticWarningCode = typeof DIAGNOSTIC_WARNING_CODES[number];

export const DIAGNOSTIC_RETRYABILITY: Readonly<Record<string, boolean>> = Object.freeze({
  EE_SQLITE_BUSY: true,
  EE_PROVIDER_RATE_LIMITED: true,
  EE_PROVIDER_TIMEOUT: true,
  EE_PROVIDER_UNAVAILABLE: true,
  EE_PACKAGE_ACTIVATION_STALE: true,
  EE_ACTIVATION_FENCING_REJECTED: true,
  EE_CONFIGURATION_POINTER_CONFLICT: true,
  EE_CONTROL_REQUEST_STALE: false,
  EE_PACKAGE_ACTIVATION_INVALID: false,
  EE_PACKAGE_ACTIVATION_WRITER_INVALID: false,
  EE_INTEGRITY_KEY_INVALID: false,
  EE_INTEGRITY_KEY_MISMATCH: false
});

export const DIAGNOSTIC_RUNTIME_ERROR_CODES = [
  "EE_PACKAGE_ACTIVATION_INVALID",
  "EE_PACKAGE_ACTIVATION_STALE",
  "EE_PACKAGE_ACTIVATION_CONFLICT",
  "EE_PACKAGE_ACTIVATION_NOT_EMPTY",
  "EE_PACKAGE_CLOSURE_REQUIRED",
  "EE_PACKAGE_ACTIVATION_SUPERVISOR_FRESH",
  "EE_PACKAGE_ACTIVATION_WRITER_INVALID",
  "EE_CONTROL_REQUEST_CONFLICT",
  "EE_CONTROL_REQUEST_STALE",
  "EE_ACTIVATION_HANDSHAKE_STALE",
  "EE_PRODUCTION_ACTIVATION_NOT_CURRENT",
  "EE_CONFIGURATION_INVALID",
  "EE_CONFIGURATION_POINTER_CONFLICT",
  "EE_CONFIGURATION_GENERATION_INVALID",
  "EE_CONFIGURATION_ACTIVATION_INVALIDATION_REQUIRED",
  "EE_PROFILE_REGISTRY_INVALID",
  "EE_PROFILE_INCOMPATIBLE",
  "EE_VALIDATION_BINDING_INVALID",
  "EE_ROUTE_AUTHORITY_INVALID",
  "EE_ROUTE_PROJECTION_WRITE_FORBIDDEN",
  "EE_ROUTE_PROJECTION_AUTHORITY_UNAVAILABLE",
  "EE_LEGACY_RULE_MODE_FORBIDDEN",
  "EE_INTEGRITY_KEY_INVALID",
  "EE_INTEGRITY_KEY_MISMATCH",
  "EE_OPENCLAW_INSTALL_ATTESTATION_INVALID",
  "EE_ACTIVATION_FENCING_REJECTED"
] as const;
