export type RuntimeProcessAuthorityErrorCode =
  | "EE_PROCESS_AUTHORITY_INVALID"
  | "EE_PROCESS_AUTHORITY_STALE"
  | "EE_PROCESS_AUTHORITY_NOT_CURRENT"
  | "EE_PROCESS_AUTHORITY_CONFLICT"
  | "EE_PROCESS_AUTHORITY_EXPIRED"
  | "EE_PACKAGE_AUTHORITY_REQUIRED"
  | "EE_LAUNCH_AUTHORIZATION_INVALID"
  | "EE_LAUNCH_AUTHORIZATION_REUSED"
  | "EE_LAUNCH_ATTEMPT_INVALID"
  | "EE_LAUNCH_ATTEMPT_STALE"
  | "EE_PROCESS_IDENTITY_MISMATCH"
  | "EE_SUPERVISOR_AUTHORITY_REQUIRED"
  | "EE_SUPERVISOR_AUTHORITY_STALE"
  | "EE_WORKER_ACQUISITION_AUTHORITY_REQUIRED"
  | "EE_WORKER_AUTHORITY_STALE"
  | "EE_WORKER_OPERATION_FORBIDDEN"
  | "EE_FORCE_TERMINATION_IDENTITY_INCOMPLETE"
  | "EE_RESTART_BUDGET_EXHAUSTED";

export class RuntimeProcessAuthorityError extends Error {
  constructor(
    public readonly code: RuntimeProcessAuthorityErrorCode,
    message: string
  ) {
    super(message);
    this.name = "RuntimeProcessAuthorityError";
  }
}
