CREATE TABLE IF NOT EXISTS scopes (
  scope_id TEXT PRIMARY KEY,
  scope_type TEXT NOT NULL,
  scope_name TEXT NOT NULL,
  root_path TEXT,
  is_disabled INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS experience_input_records (
  record_id TEXT PRIMARY KEY,
  scope_id TEXT NOT NULL,
  session_id TEXT,
  task_type TEXT NOT NULL,
  task_summary TEXT NOT NULL,
  outcome_signal TEXT NOT NULL,
  context_summary TEXT,
  evidence_json TEXT NOT NULL,
  injected_node_ids_json TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS task_runs (
  id TEXT PRIMARY KEY,
  host TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  session_id TEXT,
  task_type TEXT NOT NULL,
  task_summary TEXT NOT NULL,
  prompt_excerpt TEXT,
  context_summary TEXT,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  final_status TEXT NOT NULL,
  failure_signature TEXT,
  learning_status TEXT,
  learning_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS outcome_records (
  id TEXT PRIMARY KEY,
  task_run_id TEXT NOT NULL,
  outcome_signal TEXT NOT NULL,
  failure_signature TEXT,
  summary TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS review_events (
  id TEXT PRIMARY KEY,
  node_id TEXT NOT NULL,
  task_run_id TEXT,
  event_type TEXT NOT NULL,
  source TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hybrid_review_artifacts (
  id TEXT PRIMARY KEY,
  task_run_id TEXT NOT NULL UNIQUE,
  scope_id TEXT NOT NULL,
  worker_task TEXT NOT NULL,
  approval_class TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  route_policy_version TEXT NOT NULL,
  worker_profile_version TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  summary TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hybrid_invocation_traces (
  id TEXT PRIMARY KEY,
  surface TEXT NOT NULL,
  session_id TEXT,
  scope_id TEXT,
  worker_task TEXT,
  route TEXT NOT NULL,
  route_policy_version TEXT NOT NULL,
  capsule_schema_version TEXT,
  worker_profile_version TEXT,
  rollout_mode TEXT NOT NULL,
  rollout_reason TEXT NOT NULL,
  worker_ran INTEGER NOT NULL DEFAULT 0,
  validation_status TEXT NOT NULL,
  output_action TEXT NOT NULL,
  fallback_reason TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS experience_nodes (
  id TEXT PRIMARY KEY,
  node_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  task_type TEXT NOT NULL,
  experience_kind TEXT,
  confidence_signal TEXT,
  validation_state TEXT,
  correction_scope TEXT,
  correction_category TEXT,
  deviation_pattern TEXT,
  corrected_constraint TEXT,
  trigger_pattern TEXT NOT NULL,
  applicability_notes TEXT,
  env_signature TEXT,
  compact_hint TEXT NOT NULL,
  goal TEXT,
  recommended_steps_json TEXT,
  avoid_steps_json TEXT,
  fallback_steps_json TEXT,
  success_signal TEXT NOT NULL,
  stop_condition TEXT,
  escalation_condition TEXT,
  evidence_summary TEXT NOT NULL,
  retrieval_text TEXT,
  embedding_json TEXT,
  embedding_provider TEXT,
  embedding_model TEXT,
  embedding_version TEXT,
  embedding_dimensions INTEGER,
  distillation_mode_used TEXT,
  distillation_source TEXT,
  redistilled_from TEXT,
  promotion_signal TEXT,
  promotion_reason TEXT,
  merge_decision TEXT,
  merge_reason TEXT,
  priority_promotion_applied INTEGER NOT NULL DEFAULT 0,
  source_kind TEXT NOT NULL,
  origin_record_ids_json TEXT NOT NULL DEFAULT '[]',
  helped_record_ids_json TEXT NOT NULL DEFAULT '[]',
  harmed_record_ids_json TEXT NOT NULL DEFAULT '[]',
  state TEXT NOT NULL,
  delivery_state TEXT NOT NULL DEFAULT 'shadow_only',
  usage_count INTEGER NOT NULL DEFAULT 0,
  helped_count INTEGER NOT NULL DEFAULT 0,
  harmed_count INTEGER NOT NULL DEFAULT 0,
  consecutive_harmed_count INTEGER NOT NULL DEFAULT 0,
  last_feedback_verdict TEXT,
  support_count INTEGER NOT NULL DEFAULT 1,
  last_used_at TEXT,
  last_helped_at TEXT,
  last_harmed_at TEXT,
  quarantined_at TEXT,
  quarantine_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS experience_candidates (
  id TEXT PRIMARY KEY,
  task_run_id TEXT,
  candidate_kind TEXT,
  source_record_id TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  task_type TEXT NOT NULL,
  node_type TEXT NOT NULL,
  experience_kind TEXT,
  confidence_signal TEXT,
  validation_state TEXT,
  correction_scope TEXT,
  correction_category TEXT,
  deviation_pattern TEXT,
  corrected_constraint TEXT,
  trigger_pattern TEXT NOT NULL,
  applicability_notes TEXT,
  env_signature TEXT,
  compact_hint TEXT NOT NULL,
  goal TEXT,
  recommended_steps_json TEXT,
  avoid_steps_json TEXT,
  fallback_steps_json TEXT,
  success_signal TEXT NOT NULL,
  stop_condition TEXT,
  escalation_condition TEXT,
  evidence_summary TEXT NOT NULL,
  retrieval_text TEXT,
  source_kind TEXT NOT NULL,
  source_context_summary TEXT,
  source_outcome_signal TEXT NOT NULL,
  raw_summary TEXT,
  failure_signature TEXT,
  source_signal_json TEXT NOT NULL,
  lifecycle_state TEXT NOT NULL,
  retry_count INTEGER NOT NULL DEFAULT 0,
  distilled_node_id TEXT,
  last_error TEXT,
  promotion_signal TEXT,
  promotion_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  distilled_at TEXT,
  discarded_at TEXT,
  last_failed_at TEXT
);

CREATE TABLE IF NOT EXISTS distillation_jobs (
  id TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL,
  status TEXT NOT NULL,
  extractor_profile TEXT NOT NULL,
  distillation_source TEXT,
  failure_bucket TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  started_at TEXT,
  finished_at TEXT,
  discarded_at TEXT
);

CREATE TABLE IF NOT EXISTS injection_events (
  injection_id TEXT PRIMARY KEY,
  session_id TEXT,
  scope_id TEXT NOT NULL,
  task_type TEXT NOT NULL,
  task_summary TEXT,
  mode TEXT NOT NULL,
  delivery_mode TEXT NOT NULL DEFAULT 'live',
  delivered INTEGER NOT NULL DEFAULT 1,
  injected_node_ids_json TEXT NOT NULL,
  injection_count INTEGER NOT NULL,
  scorecard_json TEXT,
  was_successful INTEGER,
  harm_observed INTEGER,
  attribution_reason TEXT,
  created_at TEXT NOT NULL,
  resolved_at TEXT
);

CREATE TABLE IF NOT EXISTS scope_task_stats (
  scope_id TEXT NOT NULL,
  task_type TEXT NOT NULL,
  total_tasks INTEGER NOT NULL DEFAULT 0,
  success_tasks INTEGER NOT NULL DEFAULT 0,
  failed_tasks INTEGER NOT NULL DEFAULT 0,
  unknown_tasks INTEGER NOT NULL DEFAULT 0,
  injected_tasks INTEGER NOT NULL DEFAULT 0,
  injected_success_tasks INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (scope_id, task_type)
);
