import type { ExperienceEngineConfig } from "./config-schema.js";

export const defaultConfig: ExperienceEngineConfig = {
  dataDir: "./data",
  sqlitePath: "./data/sqlite/experienceengine.db",
  logLevel: "info",
  noticesInline: true,
  evaluationMode: "live",
  holdoutRate: 0.2,
  captureRawPayloads: false,
  captureDir: "./data/runtime-captures",
  maxHints: 3,
  triggerThreshold: 0.6,
  embeddingProvider: "api",
  embeddingApiProvider: "auto",
  embeddingModel: "Xenova/multilingual-e5-small",
  embeddingDtype: "q8",
  embeddingCacheDir: "./data/models/embeddings",
  retrievalRerankerMode: "auto",
  retrievalRerankerModel: "",
  distillerProvider: "openai_compatible",
  distillationAuthMode: "api_key",
  distillerModel: "",
  distillationMode: "auto",
  distillerProfile: "balanced",
  distillationAllowPassthrough: true,
  distillationMaxRetries: 2,
  distillationBatchSize: 5,
  distillationAutoDrain: true,
  hybridEnabled: false,
  hybridSyncExplainEnabled: false,
  hybridAsyncPostmortemEnabled: false,
  hybridRolloutMode: "live",
  hybridCanaryRate: 0.1,
  hybridKillSwitch: false,
  hybridRoutePolicyVersion: "hybrid-phase1-v1",
  hybridCapsuleSchemaVersion: "hybrid-capsule-v1",
  hybridExplainDecisionProfileVersion: "hybrid-explain-v1",
  hybridPostmortemReviewProfileVersion: "hybrid-postmortem-v1"
};
